version : '3.8'
services: 
    spark-master :
        container_name: spark-master-node
        hostname: spark-master         
        build:
            context : .
            dockerfile : master.Dockerfile
        ports:
            - 8080:8080
            - 7077:7077
        volumes:
            - spark-logs:/opt/spark/spark-events
            - ./workspace:/opt/hadoop/    
        environment:
            - SPARK_LOCAL_IP=spark-master
            - SPARK_MASTER_HOST=spark-master
            - SPARK_MASTER_PORT=7077
            - SPARK_MASTER_WEBUI_PORT=8080
    spark-worker-1 :
        container_name: spark-worker-node-1
        hostname: spark-worker-1
        build:
            context : .
            dockerfile : worker.Dockerfile 
        environment:
            - SPARK_LOCAL_IP=spark-worker-1
            - SPARK_WORKER_WEBUI_PORT=8081
        ports:
            - 8081:8081 
        volumes:
            - spark-logs:/opt/spark/spark-events
            - ./workspace:/opt/hadoop/     
        depends_on:
            - spark-master
    spark-worker-2 :
        container_name: spark-worker-node-2
        hostname: spark-worker-2
        build:
            context : .
            dockerfile : worker.Dockerfile 
        environment:
            - SPARK_LOCAL_IP=spark-worker-2
            - SPARK_WORKER_WEBUI_PORT=8082
        ports:
            - 8082:8082      
        volumes:
            - spark-logs:/opt/spark/spark-events 
            - ./workspace:/opt/hadoop/  
        depends_on:
            - spark-master
    spark-history-node :
        container_name: spark-history-node
        hostname: spark-history
        build:
            context : .
            dockerfile : historyServer.Dockerfile 
        ports:
            - 18080:18080 
        volumes:
            - spark-logs:/opt/spark/spark-events  
            - ./workspace:/opt/hadoop/      
        depends_on:
            - spark-master        
    jupyter:
        build:
            context : .
            dockerfile : jupyter.Dockerfile 
        ports:
         - 8888:8888
        volumes: 
         - ./workspace:/opt/hadoop/        
volumes:
    spark-logs:
    