version : '3.8'
services: 
    spark-master :
        container_name: spark-master-node 
        build:
            context : .
            dockerfile : master.Dockerfile
        ports:
            - 8080:8080
            - 7077:7077
        environments:
            - ENV SPARK_LOCAL_IP=spark-master         
    spark-worker :
        container_name: spark-worker-node-1  
        build:
            context : .
            dockerfile : worker.Dockerfile  